name: inklop_v1
description: "Plataforma de marketing de influencers y UGC."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  flutter_markdown: ^0.7.1
  auth0_flutter: ^1.14.0
  flutter_secure_storage: ^10.0.0
  http: ^1.6.0
  image_picker: ^1.2.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # 🚀 Asegúrate de que esta carpeta exista con tus .ttf
    - assets/fonts/

  # 🚀 REGISTRO DE FUENTE LOCAL (Solución al error de Geist)
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Regular.ttf
        - asset: assets/fonts/Geist-Bold.ttf
          weight: 700

# 🚀 ICONO DE LA APP
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/inklop_icon.png"
  adaptive_icon_background: "#c624da"
  adaptive_icon_foreground: "assets/images/inklop_icon.png"

# 🚀 PANTALLA DE CARGA (SPLASH)
flutter_native_splash:
  color: "#c624da"
  image: "assets/images/inklop_icon.png"
  android_12:
    image: "assets/images/inklop_icon.png"
    color: "#c624da"
  fullscreen: true